---
title: "Variables Cookbook"
author: "Hector Martin Ardanaz"
date: "Thursday, October 23, 2014"
output: html_document
---

## Feature Selection 
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

## Measures
These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

Each colums has the suffix avg() to reflect that the column is the result of calculate the average of each measure by subject and activity

tBodyAcc-XYZ_avg()
tGravityAcc-XYZ_avg()
tBodyAccJerk-XYZ_avg()
tBodyGyro-XYZ_avg()
tBodyGyroJerk-XYZ_avg()
tBodyAccMag_avg()
tGravityAccMag_avg()
tBodyAccJerkMag_avg()
tBodyGyroMag_avg()
tBodyGyroJerkMag_avg()
fBodyAcc-XYZ_avg()
fBodyAccJerk-XYZ_avg()
fBodyGyro-XYZ_avg()
fBodyAccMag_avg()
fBodyAccJerkMag_avg()
fBodyGyroMag_avg()
fBodyGyroJerkMag_avg()

The set of variables that were estimated from these signals are: 

mean(): Mean value

std(): Standard deviation

## ID Variables

Subject is the id of the subject. [1..30]

Activity is the activity the subject was doing when the measure was obtained. These are the posible values:

1 WALKING

2 WALKING_UPSTAIRS

3 WALKING_DOWNSTAIRS

4 SITTING

5 STANDING

6 LAYING
